FROM centos:6
# 签名啦
MAINTAINER openedbox "openedbox@qq.com"

RUN rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
RUN yum install nginx -y ; yum clean all
